# Generated by Django 5.2 on 2025-04-20 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('RECEPTIONIST', 'RECEPTIONIST')], default='PATIENT', max_length=15)),
                ('user_addr', models.CharField(max_length=155, null=True)),
                ('user_mobile', models.IntegerField(null=True)),
                ('user_hire_date', models.DateField(blank=True, null=True)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_specialised', models.CharField(blank=True, choices=[('EMPLANT', 'EMPLANT'), ('ORTHO', 'ORTHO')], max_length=15, null=True)),
                ('user_sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('user_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('user_bloodgroup', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
