# Generated by Django 5.2 on 2025-04-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_user_patientbilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbilling',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientBilling',
        ),
    ]
